# Generated by Django 5.0.2 on 2024-11-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0003_useraccount_groups_useraccount_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='username',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
